### PR TITLE
Fix for login problem sending users to the wrong region

### PR DESCRIPTION
**Pull request by dslake**
Login has used a substring match at login and sends users to the first matching region instead of using an exact match. It's made some regions impossible to login to based on unpredictable database query result ordering.

### CODE REVIEW

**Comment by coyled** [comment]
Dan, let me know if you want me to give you commit rights to this.

**Comment by dslake** [comment]
That would be excellent. I just poked Mic to commit this for me. Thanks.

**Comment by cmickeyb** [comment]
I'd like to take a look at this first. I think we can use both GetScene and GetScenes... there is already a sequence of attempts on login.

**Comment by dslake** [comment]
To keep existing behavior, lookup_scene_by_name could call GetScene first and then only if an exact match is not found, call GetScenes for the first "fuzzy" match. I don't like that behavior, but it's how it has always worked. The fuzzy name should never be selected over the exact match though.

**Comment by cmickeyb** [comment]
That's not what I meant. There is a sequence of attempts to resolve the
string specified in the login parameter. If the lookup by name fails (for
an exact match) then we can fall back to lookup any match.

**Comment by dslake** [comment]
This could be done in the find_start_location function. It currently looks for "last", then "home", then "uri:", etc.

**Comment by coyled** [comment]
@dslake I added you as a committer.

**Comment by dslake** [comment]
Thank you.

**Pull request merged**
